# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/bluejay/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),bluejay)

$(call add-radio-file-sha1-checked,radio/abl.img,fd6af839907f86ae4fc4280cd20fd343fc0f0c22)
$(call add-radio-file-sha1-checked,radio/bl1.img,35e61b55f0c7d8dcb19c9384adae8797f1ab86bf)
$(call add-radio-file-sha1-checked,radio/bl2.img,3c0dd360a376462a998921980f5234127b9c32ee)
$(call add-radio-file-sha1-checked,radio/bl31.img,a8f2fdb75d165d6b42a676d644f8ad0e6b156cae)
$(call add-radio-file-sha1-checked,radio/gsa.img,c56982f59224ba999c025cee346391db761c9c5b)
$(call add-radio-file-sha1-checked,radio/ldfw.img,e31beb6dae4990dc0058476fa886859fb8a64a66)
$(call add-radio-file-sha1-checked,radio/modem.img,cdba2e102900d58a0ab958ed48466db9306340a0)
$(call add-radio-file-sha1-checked,radio/pbl.img,63d817bb6c746d0050af9ade8ffbda08e2929de6)
$(call add-radio-file-sha1-checked,radio/tzsw.img,315cc98cbe142985b3595eea846d43a4007d9bd3)

endif
